package api

type Action interface {
	GetType() string
	KeepAppOpen() bool
	Run()
}

const ACTION_LIST_ACTION = "ACTION_LIST_ACTION"
const COPY_TO_CLIPBOARD_ACTION = "COPY_TO_CLIPBOARD_ACTION"
const DO_NOTHING_ACTION = "DO_NOTHING_ACTION"
const HIDE_WINDOW_ACTION = "HIDE_WINDOW_ACTION"
const LAUNCH_APP_ACTION = "LAUNCH_APP_ACTION"
const OPEN_ACTION = "OPEN_ACTION"
const OPEN_URL_ACTION = "OPEN_URL_ACTION"
const RENDER_RESULT_LIST_ACTION = "RENDER_RESULT_LIST_ACTION"
const SET_USER_QUERY_ACTION = "SET_USER_QUERY_ACTION"