package api

type Action interface {
	GetType() string
	KeepAppOpen() bool
	Run()
}

const ACTION_LIST_ACTION = "ACTION_LIST"
const COPY_TO_CLIPBOARD_ACTION = "COPY_TO_CLIPBOARD"
const DO_NOTHING_ACTION = "DO_NOTHING"
const HIDE_WINDOW_ACTION = "HIDE_WINDOW"
const LAUNCH_APP_ACTION = "LAUNCH_APP"
const OPEN_ACTION = "OPEN"
const OPEN_URL_ACTION = "OPEN_URL"
const RENDER_RESULT_LIST_ACTION = "RENDER_RESULT_LIST"
const SET_USER_QUERY_ACTION = "SET_USER_QUERY"